=== 1PlaceNZ/jboss-seam/src/main/org/jboss/seam/components-1.1.dtd
<!--

<!DOCTYPE components PUBLIC
	"-//JBoss/Seam Component Configuration DTD 1.1//EN"
	"http://jboss.com/products/seam/components-1.1.dtd">

-->

<!ELEMENT components (component|factory)*>

<!ELEMENT component (property*)>
<!ATTLIST component name CDATA #IMPLIED>
<!ATTLIST component class CDATA #IMPLIED>
<!ATTLIST component scope (stateless|request|page|conversation|session|business_process|application|STATELESS|REQUEST|PAGE|CONVERSATION|SESSION|BUSINESS_PROCESS|APPLICATION) #IMPLIED>
<!ATTLIST component jndi-name CDATA #IMPLIED>
<!ATTLIST component installed CDATA #IMPLIED>
<!ATTLIST component precedence CDATA #IMPLIED>
<!ATTLIST component auto-create (true|false) "false">

<!ELEMENT factory EMPTY>
<!ATTLIST factory name CDATA #REQUIRED>
<!ATTLIST factory method CDATA #IMPLIED>
<!ATTLIST factory value CDATA #IMPLIED>
<!ATTLIST factory scope (stateless|request|page|conversation|session|business_process|application|STATELESS|REQUEST|PAGE|CONVERSATION|SESSION|BUSINESS_PROCESS|APPLICATION) #IMPLIED>
<!ATTLIST factory auto-create (true|false) "false">

<!ELEMENT property (#PCDATA|key|value)*>
<!ATTLIST property name CDATA #REQUIRED>

<!ELEMENT key (#PCDATA)>
<!ELEMENT value (#PCDATA)>

=== 1PlaceNZ/jboss-seam/examples/jpa/resources/components.xml
<!DOCTYPE components PUBLIC
  "-//JBoss/Seam Component Configuration DTD 1.1//EN"
  "http://jboss.com/products/seam/components-1.1.dtd">

<components>
  
    <component name="org.jboss.seam.core.init">
        <property name="debug">true</property>
        <!--
        <property name="jndiPattern">#{ejbName}/local</property>
        -->
    </component>
    
    <component name="org.jboss.seam.core.manager">
        <!-- half second wait for conversation lock on concurrent requests -->
        <property name="concurrentRequestTimeout">500</property>
        <!-- 120 second conversation timeout -->
        <property name="conversationTimeout">120000</property>
        <property name="conversationIdParameter">cid</property>
        <property name="conversationIsLongRunningParameter">clr</property>
    </component>
    
    <component name="org.jboss.seam.core.pages">
        <property name="noConversationViewId">/main.xhtml</property>
    </component>
    
    <component name="bookingDatabase" 
        class="org.jboss.seam.core.EntityManagerFactory"/>
    
    <component name="em"
          class="org.jboss.seam.core.ManagedPersistenceContext">
      <!-- alernative     
      <property name="persistenceUnitJndiName">java:/jpaBookingEntityManagerFactory</property>
      -->
      <property name="entityManagerFactory">#{bookingDatabase}</property>
    </component>

</components>
